### ISSUE TITLE
SPPull is not a function

### ISSUE THREAD

**Issue by ianoel230982** [koltyakov/generator-sppp#61]
Hi,

I've just been trying out sppp with an on-prem sharepoint 2013 environment and have got the below issue.
I have followed the instructions exactly and am using the default options provided by sppp.
When i get to the 'gulp pull' command i receive the below error.

```
gulp pull

[23:38:07] Using gulpfile C:\Dev Stuff\SPPPTest\gulpfile.js
[23:38:07] Starting 'pull'...

=== Fetching files from SharePoint ===

[23:38:08] 'pull' errored after 917 ms
[23:38:08] TypeError: sppull is not a function
    at C:\Dev Stuff\SPPPTest\node_modules\sp-build-tasks\dist\tasks\sync.js:89:36
    at step (C:\Dev Stuff\SPPPTest\node_modules\sp-build-tasks\dist\tasks\sync.js:52:23)
    at Object.next (C:\Dev Stuff\SPPPTest\node_modules\sp-build-tasks\dist\tasks\sync.js:33:53)
    at fulfilled (C:\Dev Stuff\SPPPTest\node_modules\sp-build-tasks\dist\tasks\sync.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

If you could provide some guidance on this that would be great. I cannot see this issue raised before so i do not know if it is new, or whether i have missed something.

Thanks.

**Comment by koltyakov** [comment]
Hi @ianoel230982,

Please try updating `sp-build-tasks` package to v3.18.2.
